#!/bin/bash
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Needs build() not install ()
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!

install ()
{
    MODULES=""
    FILES=""
    SCRIPT="bfkf"
    add_binary "/usr/bin/openssl"
}

help ()
{
cat<<HELPEOF
  This hook allows for an openssl (bf-cbc) encrypted keyfile for LUKS.
  It relies on standard 'encrypt' hook providing decrypted '/crypto_keyfile.bin' for it.

  You must use gen-cryptkey create the encrypted enc_keyfile.bin
  The password is hashed with Whirlpool 1000 times
  Then your password + Hash is used to encrypt the keyfile

  mkinitcpio.conf:
  MODULES: add ext4 vfat or whatever the type of filesystem the keyfile is on
  HOOKS=" ... usb bfkf encrypt ... filesystems ..."

  Kernel Parameters:
  There is no need for cryptkey=

  Two options are supported:
  1) Using a file on the device:
     bfkf=<device>:<fs-type>:<path>
  2) Reading raw data from the block device:
     bfkf=<device>:<offset>:<size>

  Example: /etc/default/grub
  GRUB_CMDLINE_LINUX="bfkf=/dev/sdb1:ext4:/keyfile.bin cryptdevice=/dev/sda2:root"
HELPEOF
}